#!/bin/bash
#PBS -A USNAM37752431
#PBS -q standard
#PBS -l select=4:ncpus=12:mpiprocs=12
#PBS -l walltime=01:00:00
#PBS -l ccm=1
#PBS -N nfc_phi_dev
#PBS -j oe
#PBS -V
#PBS -S /bin/bash
cd $WORKDIR
JOBID=`echo $PBS_JOBID | cut -d '.' -f 1`
if [ ! -d $JOBID ]; then
mkdir -p $JOBID
fi
cd $JOBID
cp $PBS_O_WORKDIR/turbineSim .
cp $PBS_O_WORKDIR/snl.lbm .
cp $PBS_O_WORKDIR/inl.lbm .
cp $PBS_O_WORKDIR/onl.lbm .
cp $PBS_O_WORKDIR/params.lbm .
cp $PBS_O_WORKDIR/process_lbm_data.py .
cp $PBS_O_WORKDIR/process_lbm_data_mpi.py .
cp $PBS_O_WORKDIR/vtkHelper.py .
cp $PBS_O_WORKDIR/gold_standard.npy .
cp $PBS_O_WORKDIR/validate_r3.py .
export OMP_NUM_THREADS=1
aprun -B ./turbineSim 
